        pool:
          vmImage: 'ubuntu-1604' # set to windows-latest or another Windows vmImage for Windows builds

        variables:
          imageName: 'pipelines-javascript-docker'

        steps:
          task: UseDotNet@2
            displayName: 'Install .NET Core SDK'
            inputs:
              version: 5.0.x
              performMultiLevelLookup: true
              includePreviewVersions: true # Required for preview versions